[target.aarch64-apple-darwin]
rustflags = ["--cfg", "aes_armv8", "--cfg", "polyval_armv8"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["--cfg", "aes_armv8", "--cfg", "polyval_armv8"]

[target.aarch64-unknown-linux-musl]
rustflags = ["--cfg", "aes_armv8", "--cfg", "polyval_armv8"]
